### ISSUE TITLE
Fuzzy test gfx-memory

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-extras#19]
Blocked on https://github.com/gfx-rs/gfx/issues/3278
We should have tests that just spam a whole ton of allocations with various randomized memory requirements.

**Comment by GabrielMajeri** [comment]
Should this be implemented simply as `#[test]`s which use `rand` to generate random allocations, or should this be done using a framework like `cargo-fuzz` / `afl.rs`?

**Comment by kvark** [comment]
@GabrielMajeri Good question! I haven't used the fuzzers yet, but I'd love to see us trying them out. We'd definitely need to fuzz Naga, so might as well try them here. The answer is - up to the hero implementing this :)
